# deploy me with docker stack deploy -c docker-compose.yml killer-game
version: "3"
services:
    api:
      image: arousseau/killer-game-api
      build:
        dockerfile: api.Dockerfile
        context: .
      volumes:
        - "$PWD/db:/app/api/db"
      deploy:
          replicas: 1
          resources:
              limits:
                  memory: 50M
          restart_policy:
              condition: on-failure
      ports:
       - "3001:3001"

    frontend:
      image: arousseau/killer-game-frontend
      build:
        dockerfile: frontend.Dockerfile
        context: .
      deploy:
          replicas: 1
          resources:
              limits:
                  memory: 500M
          restart_policy:
              condition: on-failure
      ports:
          - "3000:3000"