
@game_id=b699f694-ac4f-46fe-adb4-4f44ccbf7164
@game_private_token=b0fc4e52-018e-4c9b-bdc9-df5410c6780b

###

POST http://localhost:3000/games
Content-Type: application/json

{
  "name": "My first game",
  "actions": [
    "action 1",
    "actions 2"
  ]
}

###

PUT http://localhost:3000/games/{{game_private_token}}
Content-Type: application/json

{
  "name": "My first game updated",
  "actions": [
    "action 1",
    "actions 2"
  ]
}

###

GET http://localhost:3000/games/{{game_public_token}}

###

GET http://localhost:3000/games/{{game_public_token}}/players

###

POST http://localhost:3000/games/{{game_id}}/players
Content-Type: application/json

{
  "name": "John Doe"
}

###

GET http://localhost:3000/games/{{game_id}}/players
Authorization: {{game_private_token}}

###