
@game_public_token=add42ad1-e294-4078-9c1b-389934bced80
@game_private_token=8ba27422-a79b-4675-b0f7-4abf4f3f9c4d

###

POST http://localhost:3000/games
Content-Type: application/json

{
  "name": "My first game",
  "actions": [
    "action 1",
    "actions 2"
  ]
}

###

GET http://localhost:3000/games/{{game_public_token}}

###

GET http://localhost:3000/games/{{game_public_token}}/players

###

GET http://localhost:3000/admin/games/{{game_private_token}}

###

POST http://localhost:3000/games/{{game_public_token}}/players
Content-Type: application/json

{
  "name": "John Doe"
}

###

GET http://localhost:3000/games/by-public-token/{{game_public_token}}/players

###

POST http://localhost:3000/games
Content-Type: application/json

{
  "name": "My first game",
  "actions": [
    "action 1",
    "actions 2"
  ]
}

###