name: build

on: [push]

# on:
#   push:
#     branches:
#       - main

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker build
        run: docker build . -f "api.Dockerfile" -t "arousseau/killer-game-api:${{github.sha}}"

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Docker push
        run: docker push "arousseau/killer-game-api:${{github.sha}}"


      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20.x"

      # - run: npm ci
      #   working-directory: ./api

      # - run: npm run test
      #   working-directory: ./api
